source 'http://gemcutter.org'

gem 'sinatra'
gem 'erector'
gem 'sass'
gem 'redcarpet', '2.0.0b5'
gem 'pygments.rb'
gem 'twitter'
gem 'twitter-text'
gem 'ratom', :git => 'git://github.com/icambron/ratom.git'
gem 'i18n'
gem 'spandex', :git => 'git://github.com/icambron/spandex.git'