source 'http://gemcutter.org'

gem 'sinatra'
gem 'erector'
gem 'sass'
gem 'redcarpet', '2.0.0b3'
gem 'pygments.rb'
gem 'twitter', :git => 'git://github.com/icambron/twitter.git'
gem 'twitter-text'
gem 'ratom', :git => 'git://github.com/icambron/ratom.git'