source 'http://gemcutter.org'

gem 'sinatra'
gem 'erector'
gem 'sass'
gem 'redcarpet', '2.0.0b3'
gem 'pygments.rb'
gem 'twitter'
gem 'twitter-text'
gem 'atom', :git => 'git://github.com/icambron/ratom.git'
